import './globals.css'
import { Inter } from 'next/font/google'

import { Navigation } from '@/components/Navigation/Navigation';

const inter = Inter({ subsets: ['latin'] })
const pages = require.context('./', true,/^(?!src\/app).*page.tsx/).keys();

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation pages={pages}/>
        {children}
      </body>
    </html>
  )
}
